
<style >

.text-left
{
    text-align: left !important;
}


* {box-sizing: border-box}


/* Style tab links */
.tablink {
  background-color: #4ca1f6;
  color: white;
  float: left;
  border: none;
  outline: none;
  cursor: pointer;
  padding: 8px 1px;
  font-size: 17px;
  width: 30%;
  
}

.tablink:hover {
  background-color: #777;
}

/* Style the tab content (and add height:100% for full page content) */
.tabcontent {
  color: black;
  display: none;
  padding: 80px 20px;
  height: 100%;
}


.bold
{

    font-weight: bold;
}

#Home {background-color: white;}
#News {background-color: white;}
#Contact {background-color: white;}
#About {background-color: white;}
</style>


<div class="content-wrapper" style="min-height: 946px;">
    <section class="content-header">
        <h1>
    <i class="fa fa-map-o"></i> <?php echo $this->lang->line('termsandcondition'); ?> <small></small>  
        </h1>
    </section>



   
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title"><i class="fa fa-search"></i> <?php echo $this->lang->line('termsandcondition'); ?></h3>
                        <br>
                        <small>Payment Policy</small>
                        </div>

                        <div class="box-body">
                        <div class="kode_contact_des">
                        <div class="container">
                            



            
<div class="kode_contact_service">

<button class="tablink" onclick="openPage('Home', this, '#0c4e8f')">DISCLAIMER POLICIES</button>
<button class="tablink" onclick="openPage('News', this, '#0c4e8f')" id="defaultOpen">PRIVACY POLICY</button>
<button class="tablink" onclick="openPage('Contact', this, '#0c4e8f')">REFUND POLICY</button>
<!--<button class="tablink" onclick="openPage('About', this, 'orange')">About</button>-->

<div id="Home" class="tabcontent" style="text-align:left;">
    <p>
  <h4 style="text-align:center;"><span class="bold">DISCLAIMER POLICIES</span></h4>
  <span class="bold">Disclaimer policy</span><br>
</p>
  <p>

IRITAQ hereby grants you access to https://www.iritaq.info/. ("The Website") . Definitions and key terms To help explain things as clearly as possible in this Disclaimer, every time any of these terms are referenced, are strictly defined as: • Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, and remember information about you such as your language preference or login information. • Company: when this policy mentions "Company," "we," "us," or "our," it refers to IRITAQ that is responsible for your information under this Disclaimer. • Service: refers to the service provided by IRITAQ as described in the relative terms (if available) and on this platform. • Website: IRITAQ's site, which can be accessed via this URL: https://www.iritaq.info/ • You: a person or entity that is registered with IRITAQ to use the Services.</p>


<p>


<span class="bold">Errors and Omissions Disclaimer </span><br>
</p>

<p>
We are not responsible for any content, code or any other imprecision. We reserve the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.</p>

<p> 
<span class="bold">General Disclaimer</span><br><br>


 The IRITAQ Service and its contents are provided "as is" and "as available" without any warranty or representations of any kind, whether express or implied. as such, IRITAQ exercises editorial control over content and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via the IRITAQ Service. Without limiting the foregoing, IRITAQ specifically disclaims all warranties and representations in any content transmitted on or in connection with the IRITAQ Service or on sites that may appear as links on the IRITAQ institution or in the activities provided as a part of, or otherwise in connection with, the IRITAQ Service, including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information given by IRITAQ or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing, IRITAQ does not warrant that the IRITAQ Service will be uninterrupted, uncorrupted, timely, or error-free. Educational Disclosure Any Information provided by IRITAQ is for educational purposes only, and is not to be interpreted as a recommendation for a specific treatment plan, product, or course of action. We are a distributor and not a publisher of the content supplied by third parties, as such, We exercise no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information or educational content provided through or accessible via IRITAQ. Without limiting the foregoing, We specifically disclaim all warranties and representations in any content transmitted on or in connection with us or on sites that may appear as links on our platform, or in the products provided as a part of, or otherwise in connection with us. No oral advice or written information given by us or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Your Consent We've updated our Disclaimer to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our service, registering an account, or making a purchase, you hereby consent to our Disclaimer and agree to its terms.
</p>
<p>
<span class="bold">Changes To Our Disclaimer </span><br>
</p>
<p>
Should we update, amend or make any changes to this document so that they accurately reflect our Service and policies. Unless otherwise required by law, those changes will be prominently posted here. Then, if you continue to use the Service, you will be bound by the updated Disclaimer. If you do not want to agree to this or any updated Disclaimer, you can delete your account. Contact Us Don't hesitate to contact us if you have any questions.<br>
 • Via Email: https://www.iritaq.info/# <br>
• Via Phone Number: 9847232786 <br>
• Via this Link: https://www.iritaq.info/<br>
</p>

</div>





<div id="News" class="tabcontent" style="text-align:left;">
    <p>
  <h4 style="text-align:center;"><span class="bold">PRIVACY POLICY</h4>
  </span>
</h4>
</p>

  <p><span class="bold">SUMMARY OF KEY POINTS</span>
  </p>
  <p>

This summary provides key points from our privacy notice, but you can find out more details about any of these topics by clicking the link following each key point or by using our table of contents below to find the section you are looking for. You can also click here to go directly to our table of contents.</p><p>
What personal information do we process? When you visit, use, or navigate our Services, we may process personal information depending on how you interact with https://www.iritaq.info/ and the Services, the choices you make, and the products and features you use. Click here to learn more.</p><p>
Do we process any sensitive personal information? We do not process sensitive personal information.</p><p>
Do we receive any information from third parties? We do not receive any information from third parties.</p><p>
How do we process your information? We process your information to provide,</p><p>
improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law. We may also process your information for other purposes with your consent. We process your information only when we have a valid legal reason to do so. Click here to learn more.</p><p>
In what situations and with which parties do we share personal information?</p><p>
We may share information in specific situations and with specific third parties. Click here to learn more.</p><p>
What are your rights? Depending on where you are located geographically, the applicable privacy law may mean you have certain rights regarding your personal information. Click here to learn more.</p><p>
How do you exercise your rights? The easiest way to exercise your rights is by Filling out our data subject request form available here or by contacting us. We will consider and act upon any request in accordance with appliCcaobmlepdllaitaance Checklist</p><p>

<span class="bold">TABLE OF CONTENTS</span></p><p>
1.  WHAT INFORMATION DO WE COLLECT?<br>
2.  HOW DO WE PROCESS YOUR INFORMATION?<br>
3.  WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?<br>
4.  DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?<br>
5.  HOW LONG DO WE KEEP YOUR INFORMATION?<br>
6.  HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?<br>

</p>
<p>

1.  WHAT INFORMATION DO WE COLLECT?<br></p>
<p>
Personal information you disclose to us
In Short: We collect personal information that you provide to us.
We collect personal information that you voluntarily provide to us when you express an interest in obtaining information about us or our products and Services, when you participate in activities on the Services, or otherwise when you contact us.Personal Information Provided by You. The personal information that we collect depends on the context of your interactions with us and the Services, the choices you make, and the products and features you use. The personal information we collect
may include the following:</p>
<p>
<br>
names:<br><br>
phone numbers:<br><br>
billing addresses:<br><br>
contact or authentication data:<br><br>
contact preferences:<br><br>
passwords:<br><br>
job titles:<br><br>
mailing addresses:<br><br>
email addresses:<br><br>
usernames:<br><br>
Sensitive Information. We do not process sensitive information.<br><br>
</p>
<p>

Payment Data. We may collect data necessary to process your payment if you make payment, such as your payment instrument number (such as a credit card number), and the security code associated with your payment instrument. All payment data is stored by 
</p><p>

. You may find their privacy notice link(s) here:
</p><p>
All personal information that you provide to us must be true, complete, and accurate, and you must notify us of any changes to such personal information.
</p><p>
2.  HOW DO WE PROCESS YOUR INFORMATION?<br></p><p>

In Short: We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply</p><p>
with law. We may also process your information for other purposes with your consent.</p><p>

We process your personal information for a variety of reasons, deCCpeonmdipnllgiaonnce Checklist</p><p>
how you interact with our Services, including:</p><p>
 To send administrative  information to you. We may process your information to send you details about our products and services, changes to our terms and policies, and other similar information.</p><p>
To enable user-to-user communications. We may process your information if you choose to use any of our offerings that allow for communication with another user.</p><p>
To request feedback. We may process your information when necessary to request feedback and to contact you about your use of our Services.</p><p>
To administer prize draws and competitions. We may process your information to administer prize draws and competitions.</p>

3.  WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?<br></p><p>

In Short: We may not any share information in any situations with a third party or with other entity.</p><p>

4.  DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?<br></p><p>

In Short: We may use cookies and other tracking technologies to collect and store your information.</p><p>
We may use cookies and similar tracking technologies (like web beacons and pixels) to access or store information. Specific information about how we use such technologies and how you can refuse certain cookies is set out in our Cookie Notice.</p><p>
5.  HOW LONG DO WE KEEP YOUR INFORMATION?<br></p><p>

In Short: We keep your information for as long as necessary to fulfil the purposes outlined in this privacy notice unless otherwise required by law. We will only keep your personal information for as long as it is necessary for the purposes set out in this privacy notice, unless a longer retention period is required or permitted by law (such as tax, accounting, or other legal requirements).</p><p>

6.  DO WE COLLECT INFORMATION FROM MINORS?<br></p><p>

In Short: We do not knowingly collect data from or market to children under 18 years of age.
We do not knowingly solicit data from or market to children under 18 years of age. By using the Services, you represent that you are at least 18 or that you are the parent or guardian of such a minor and consent to such minor dependent’s use of the Services. If we learn that personal information from users less than 18 years of age has been collected, we will deactivate the account and take reasonable measures to promptly delete such data from our records. If you become aware of any data we may have collected from children under age 18, please contact us.
</p> 
</div>





<div id="Contact" class="tabcontent" style="text-align:left;">

<p>
 <h4 style="text-align:center;"><span class="bold">REFUND POLICY</span></h4>
</p>

  <p><h4 style="text-align:left;"><span class="bold">Refund policy</span></h4></p>
  <p>
The institution has a few options for ending a programme and getting your money back, as detailed in the Refund PC.
The reimbursement sum will be electronically paid to the credit/debit/net be account used make the payment.</p><p>

<span class="bold">Registration Fee, Admission Cancellation, and Fee Refund</span><br><br>
1.  If no other details are stated, a non-refundable registration fee of Rs. 100 will also be imposed.<br>
2.  At the time of admission, there is a first semester/year programme cost.<br>
3.  If a student requests cancellation of admission and a return of fees, the request shall be assessed in accordance with the following institution policy:<br>
4.  Before the deadline for submitting an application, the fee will be reimbursed less a fee of Rs. 100. Within 15 days of the deadline for submitting an application,<br>
5.  The payment will be refunded within 15 days of the deadline for submitting the admission form, less a deduction of Rs. 150.<br>
6.  No refunds will be granted after 30 days have passed since the last date was closed.
</p>
</div>

<!--<div id="About" class="tabcontent">
  <h3>About</h3>
  <p>Who we are and what we do.</p>
</div>-->

<script>
function openPage(pageName,elmnt,color) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablink");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].style.backgroundColor = "";
  }
  document.getElementById(pageName).style.display = "block";
  elmnt.style.backgroundColor = color;
}

// Get the element with id="defaultOpen" and click on it
document.getElementById("defaultOpen").click();
</script>
                                



                            </div>
                            

</div>
</div>



                        
                    </div>                   
            </div>
        </div>
    </div>
    </section>
</div>




